version: '3.1'
services:
  database_dev:
    image: mysql:5.7
    container_name: database_marvel_dev
    volumes:
      - ./database/dev:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=M4rv3lD4t4BaS3
      - MYSQL_ROOT_PASSWORD=M4rv3lD4t4BaS3R00t
      - MYSQL_DATABASE=marvel_database

volumes:
  dev:

