version: '3'
services:
  marvel_stone_api:
    container_name: marvel_stone_api
    build:
      context: .
      dockerfile: Dockerfile
    image: stone-marvel-api
    env_file: .env
    depends_on: 
      - database
    networks:
      - stone-network
    ports:
      - 3000:3000
    restart: on-failure

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./docker-database/dev:/var/lib/mysql
    networks:
      - stone-network
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=M4rv3lD4t4BaS3
      - MYSQL_ROOT_PASSWORD=M4rv3lD4t4BaS3R00t
      - MYSQL_DATABASE=marvel_database

  database_test:
    image: mysql:5.7
    container_name: database_test
    volumes:
      - ./docker-database/test:/var/lib/mysql
    networks:
      - stone-network
    ports:
      - 3307:3306
    restart: on-failure
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=TestM4rv3lD4t4BaS3
      - MYSQL_ROOT_PASSWORD=TestM4rv3lD4t4BaS3R00t
      - MYSQL_DATABASE=marvel_database



networks:
  stone-network:
    driver: bridge

volumes:
  dev:

