version: '3'
services:
  marvel_stone_api:
    container_name: marvel_stone_api
    build:
      context: .
      dockerfile: Dockerfile
    image: stone-marvel-api
    depends_on: 
      - database
    networks:
      - stone-network
    ports:
      - ${APP_PORT}:3000
    restart: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - AUTHENTICATION_SECRET_KEY=${AUTHENTICATION_SECRET_KEY}
      - APP_PORT=${APP_PORT}

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ${DOCKER_CONTAINER_PATH}:/var/lib/mysql
    networks:
      - stone-network
    ports:
      - ${DB_PORT}:3306
    restart: on-failure
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_NAME}

  database_test:
    image: mysql:5.7
    container_name: database_test
    volumes:
      - ${DOCKER_CONTAINER_PATH}:/var/lib/mysql
    networks:
      - stone-network
    ports:
      - ${DB_PORT}:3306
    restart: on-failure
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_NAME}


networks:
  stone-network:
    driver: bridge

volumes:
  dev:

